import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { existsSync, mkdirSync, copyFileSync, watch } from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const devOutDir = 'testvault/testvault/.obsidian/plugins/explorer-order-editor';

// The two files the plugin folder needs that esbuild does not produce.
const assets = ['manifest.json', 'styles.css'];

const copyAssets = () => {
	if (!existsSync(devOutDir)) {
		mkdirSync(devOutDir, { recursive: true });
	}
	for (const asset of assets) {
		copyFileSync(asset, `${devOutDir}/${asset}`);
	}
};

/**
 * Parses styles.css and reports any syntax problem, returning how many it
 * found.
 *
 * Nothing else in the toolchain looks at CSS at all: eslint, tsc and vitest
 * all passed cleanly on a styles.css whose comment had a stray `*​/` in the
 * middle of it. A CSS parser recovers from that by discarding everything up
 * to the next block — which silently deleted a whole rule — and the only
 * thing that caught it was a screenshot of the running plugin.
 *
 * esbuild does parse CSS, but treats syntax errors in a stylesheet passed as
 * an entry point as *warnings* and still exits 0, so the failure has to be
 * raised by hand here.
 */
const validateStyles = async () => {
	const result = await esbuild.build({ entryPoints: ['styles.css'], write: false, logLevel: 'silent' });
	if (result.warnings.length > 0) {
		const formatted = await esbuild.formatMessages(result.warnings, { kind: 'warning', color: true, terminalWidth: 100 });
		process.stderr.write(`styles.css failed to parse:\n${formatted.join('')}`);
	}
	return result.warnings.length;
};

/** @type {import('esbuild').Plugin} */
const copyToVaultPlugin = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			copyAssets();
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: prod ? 'main.js' : `${devOutDir}/main.js`,
	minify: prod,
	plugins: prod ? [] : [copyToVaultPlugin],
});

if (prod) {
	await context.rebuild();
	// After the bundle, so a CSS problem can't mask a real TypeScript failure,
	// but still fatal: styles.css ships in the release exactly as written.
	process.exit((await validateStyles()) > 0 ? 1 : 0);
} else {
	await context.watch();

	// Reported but never fatal in dev — killing the watch over a stylesheet
	// that is mid-edit would be worse than the broken rule it is complaining
	// about. Hot Reload still picks the file up either way; this only makes
	// sure a mistake is on screen the moment it is saved.
	await validateStyles();

	// esbuild only rebuilds when something in the *module graph* changes, and
	// neither styles.css nor manifest.json is imported by any TypeScript file.
	// So the onEnd copy above never fires for a CSS-only edit, and the test
	// vault keeps whichever stylesheet it got from the last code change —
	// hand-testing then silently runs against stale styles. Watching the
	// directory rather than each file keeps working when an editor saves by
	// replacing the file (the new file has a new inode, which a per-file watch
	// would stop hearing from).
	watch('.', (_event, filename) => {
		if (filename === null || !assets.includes(filename)) return;
		copyAssets();
		if (filename === 'styles.css') void validateStyles();
	});
}
