import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { existsSync, mkdirSync, copyFileSync, watch } from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const devOutDir = 'testvault/testvault/.obsidian/plugins/explorer-order-editor';

// The two files the plugin folder needs that esbuild does not produce.
const assets = ['manifest.json', 'styles.css'];

const copyAssets = () => {
	if (!existsSync(devOutDir)) {
		mkdirSync(devOutDir, { recursive: true });
	}
	for (const asset of assets) {
		copyFileSync(asset, `${devOutDir}/${asset}`);
	}
};

/** @type {import('esbuild').Plugin} */
const copyToVaultPlugin = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			copyAssets();
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: prod ? 'main.js' : `${devOutDir}/main.js`,
	minify: prod,
	plugins: prod ? [] : [copyToVaultPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();

	// esbuild only rebuilds when something in the *module graph* changes, and
	// neither styles.css nor manifest.json is imported by any TypeScript file.
	// So the onEnd copy above never fires for a CSS-only edit, and the test
	// vault keeps whichever stylesheet it got from the last code change —
	// hand-testing then silently runs against stale styles. Watching the
	// directory rather than each file keeps working when an editor saves by
	// replacing the file (the new file has a new inode, which a per-file watch
	// would stop hearing from).
	watch('.', (_event, filename) => {
		if (filename !== null && assets.includes(filename)) copyAssets();
	});
}
