import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { existsSync, mkdirSync, copyFileSync } from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const devOutDir = 'testvault/testvault/.obsidian/plugins/explorer-order-editor';

/** @type {import('esbuild').Plugin} */
const copyToVaultPlugin = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			if (!existsSync(devOutDir)) {
				mkdirSync(devOutDir, { recursive: true });
			}
			copyFileSync('manifest.json', `${devOutDir}/manifest.json`);
			copyFileSync('styles.css', `${devOutDir}/styles.css`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: prod ? 'main.js' : `${devOutDir}/main.js`,
	minify: prod,
	plugins: prod ? [] : [copyToVaultPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
